### ISSUE TITLE
Optional 이란 무엇인지 설명하시오.

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#1]
2021년 2월 18일(목) 오후 7시까지

**Comment by IMCHO** [comment]
[여기서](https://www.notion.so/taeknology/Optional-e78e3efcf88243bbb015ca074895967a) 확인해주세요.

**Comment by jeffoio** [comment]
https://www.notion.so/Optional-7e495dec684a4a258f50759161c2995a

**Comment by Minimoa** [comment]
[optional 정리](https://velog.io/@alslahdk/swift-Optionals) ....😀

**Comment by kartmon61** [comment]
https://www.notion.so/Optional-ac9abaf283c04df79204ca3e68356f4c

**Comment by jwonyLee** [comment]
내용이 길어진 김에 블로그 포스팅으로 해봤습니다ㅋㅋ 
글의 뼈대는 딱 한 달전에 챌린지 진행중에 쓰고 있었는데, 어쩌다보니 인터뷰 질문 쓰면서 쓰게 되었네요!
[Swift-Optional과-Optional-안전하게-사용하기](https://jwonylee.tistory.com/entry/Swift-Optional과-Optional-안전하게-사용하기)

**Comment by devejs** [comment]
[옵셔널](https://devejs.github.io/ios/2020/09/07/swift-optional.html)
