### ISSUE TITLE
MVC 구조에 대해 블록 그림을 그리고, 각 역할과 흐름을 설명하시오.

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#10]
2020년 9월 29일(화) 오전 10시 까지

**Comment by jwonyLee** [comment]
https://www.notion.so/jwonylee/MVC-dc71851494e84fad82d298e9e6f7a808

**Comment by devejs** [comment]
https://devejs.github.io/ios/2020/09/28/ios-mvc.html

**Comment by Minimoa** [comment]
https://www.notion.so/767473/MVC-050733631dac44ee8cd23c1418d01b5e

**Comment by seonyoung169** [comment]
https://www.notion.so/MVC-e0961c3835f1412d9de89997fd05e8b8

**Comment by getBingsoo** [comment]
https://www.notion.so/MVC-e1b9d0bf28984f77940abe22e283c375
