### ISSUE TITLE
프로토콜이란 무엇인지 설명하시오.

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#11]
2020년 10월 1일(목) 오전 10시 까지

**Comment by jeffoio** [comment]
https://www.notion.so/Protocol-da59e9f332174346ada881526e1e419d

**Comment by jwonyLee** [comment]
https://www.notion.so/jwonylee/1269bf21c4884ae697f5152b2647eedd

**Comment by Minimoa** [comment]
https://www.notion.so/767473/9edd019a69e445dfb2db44752ecc21e0

**Comment by IMCHO** [comment]
https://www.notion.so/taeknology/4bb0e3c581234f829a73c3c4945d5825

**Comment by devejs** [comment]
https://devejs.github.io/ios/2020/10/03/swift-protocol.html

**Comment by seonyoung169** [comment]
https://www.notion.so/a535d24321cc43bd9f29a91eacfc5cbd

**Comment by getBingsoo** [comment]
https://www.notion.so/6c83fc3dab0e43488ffcaa82f6250b8c
