### ISSUE TITLE
Hashable이 무엇이고, Equatable을 왜 상속해야 하는지 설명하시오.

### ISSUE THREAD

**Issue by IMCHO** [ios-study-boost/iOSInterviewquestions#12]

**Comment by Minimoa** [comment]
https://www.notion.so/767473/Hashable-Equatable-852108cfdbb0411ca5158317af807458

**Comment by jeffoio** [comment]
https://www.notion.so/Hashable-Equatable-12-e0a1aa893bff4a3ca4d4e01602f46141

**Comment by IMCHO** [comment]
https://www.notion.so/taeknology/Hashable-Equatable-aeab02dd6bae4049b3ecd812a4332cca

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/Hashable-Equatable.md

**Comment by devejs** [comment]
https://devejs.github.io/ios/2020/10/07/swift-hashable.html

**Comment by kartmon61** [comment]
https://www.notion.so/Hashable-Equatable-8d8694a71b2240f7805d66675d512549

**Comment by seonyoung169** [comment]
https://www.notion.so/Hashable-Equatable-c35930117754402a82237eb8781a3cd2
