### ISSUE TITLE
mutating 키워드에 대해 설명하시오.

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#13]
2020년 10월 11일(일) 오후 1시까지

**Comment by devejs** [comment]
https://devejs.github.io/ios/2020/10/08/swift-mutating.html

**Comment by jeffoio** [comment]
https://www.notion.so/mutating-b8dee7a6e15e47778f31d771aae58eae

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/Mutating.md

**Comment by IMCHO** [comment]
https://www.notion.so/taeknology/mutating-571bdfcc88964e71bcdbb19387ed36d7

**Comment by Minimoa** [comment]
https://www.notion.so/767473/mutating-43e6b502b6fb4373a5fa5516d20cf3e3

**Comment by Minimoa** [comment]
https://www.notion.so/767473/mutating-43e6b502b6fb4373a5fa5516d20cf3e3

**Comment by seonyoung169** [comment]
https://www.notion.so/mutating-af59005394cb48b5be10933331d6c565
