### ISSUE TITLE
탈출 클로저에 대하여 설명하시오.

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#14]
2020년 10월 11일(일) 오후 1시까지

**Comment by jeffoio** [comment]
https://www.notion.so/fc7ca401197545beb974a45142170c60

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/Escaping-Closure.md

**Comment by IMCHO** [comment]
https://www.notion.so/taeknology/92cace03b7b544cea95fc05ae583acd3

**Comment by Minimoa** [comment]
https://www.notion.so/767473/06ea67a321494f23a74b10e7981aabfd

**Comment by devejs** [comment]
https://devejs.github.io/ios/2020/10/10/swift-escaping-closure.html

**Comment by seonyoung169** [comment]
https://www.notion.so/e5b4a11b055242f7a8d64bb87cd81c3c
