### ISSUE TITLE
Extension에 대해 설명하시오.

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#15]
2020년 10월 13일(화) 오전 10시 까지

**Comment by IMCHO** [comment]
https://www.notion.so/taeknology/Extension-6d55cddb71e34973bbf6b670b87af74f

**Comment by jeffoio** [comment]
https://www.notion.so/Extension-b6803bd78ee34f82801814d903b9aa14

**Comment by devejs** [comment]
https://devejs.github.io/ios/2020/10/12/swift-extension.html

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/Extension.md

**Comment by Minimoa** [comment]
https://www.notion.so/767473/Extension-462b75159d0140208620315d282c6fbb

**Comment by seonyoung169** [comment]
https://www.notion.so/Extension-78086f6a62414e059b9609ccef3eceae
