### ISSUE TITLE
접근 제어자의 종류엔 어떤게 있는지 설명하시오

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#16]
2020년 10월 15일(목) 오전 10시까지

**Comment by IMCHO** [comment]
https://www.notion.so/taeknology/ee7046ee4b614f2cad950776445f6268

**Comment by jeffoio** [comment]
https://www.notion.so/bb039b0999764622b66b8c90df2ec1f7

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/Access-Modifier.md

**Comment by Minimoa** [comment]
https://www.notion.so/767473/dab4a6aef2e043378e9e2156ca70a00d

**Comment by devejs** [comment]
https://devejs.github.io/ios/2020/10/14/swift-access-control.html

**Comment by seonyoung169** [comment]
https://www.notion.so/135a86e60b01424a87e293abc07e0387
