### ISSUE TITLE
defer란 무엇인지 설명하시오.

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#17]
2020년 10월 16일(금) 오후 3시 30분까지

**Comment by Minimoa** [comment]
https://www.notion.so/767473/defer-4fb3a35176714a94ab4c4ff4ffd09815

**Comment by IMCHO** [comment]
https://www.notion.so/taeknology/defer-defer-defer-9fb2ae3a9ad749019b95c11db2773b35
2개 한꺼번에 작성했습니다!

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/defer.md

**Comment by devejs** [comment]
https://devejs.github.io/ios/2020/10/15/swift-deter.html 
저도 두개 한꺼번에 작성했습니다!

**Comment by jeffoio** [comment]
https://www.notion.so/defer-51013342c2b44b329995bc4841989cba

**Comment by seonyoung169** [comment]
https://www.notion.so/defer-defer-defer-029ed35db4da45949365600bbdfadde6
