### ISSUE TITLE
Bounds 와 Frame 의 차이점을 설명하시오.

### ISSUE THREAD

**Issue by jeffoio** [ios-study-boost/iOSInterviewquestions#19]
2020년 10월 20일(화) 오전 10시 까지

**Comment by jeffoio** [comment]
https://www.notion.so/Bounds-Frame-404be8dfa4a645169012d783a04c3883

**Comment by IMCHO** [comment]
https://www.notion.so/taeknology/Bounds-Frame-af7b75953e914423a1fb6f8edc4943e6

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/Bounds-Frame.md

**Comment by devejs** [comment]
https://devejs.github.io/ios/2020/10/19/ios-bound-frame.html

**Comment by getBingsoo** [comment]
https://www.notion.so/9894cee5d66640cb8c5fa984ea4f1c6c
