### ISSUE TITLE
Fast Enumeration 이란 무엇인지 설명하시오.

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#2]
2021년 2월 22일(월) 오후 8시까지

**Comment by IMCHO** [comment]
https://www.notion.so/taeknology/Fast-Enumeration-775e3191ec4f4cdfba5dedc651f67c07

**Comment by Minimoa** [comment]
https://www.notion.so/767473/Fast-Enumeration-f302aba2b0b64d4396d95bffb5e3de09

**Comment by jwonyLee** [comment]
https://www.notion.so/jwonylee/Fast-Enumeration-541517122254456c99a768db9537064d

**Comment by jeffoio** [comment]
https://www.notion.so/Fast-Enumeration-019686f7bcd441bd90d2cf6d6dfdabcb

**Comment by devejs** [comment]
[왜 다 노션을 쓰시는 거ㅇ에요](https://devejs.github.io/ios/2020/09/10/swift-fast-enumeration.html)

**Comment by kartmon61** [comment]
https://www.notion.so/Fast-Enumeration-e2d19491e0504280895df9d426875aeb
