### ISSUE TITLE
실제 디바이스가 없을 경우 개발 환경에서 할 수 있는 것과 없는 것을 설명하시오.

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#20]
2020년 10월 22일(목) 오전 10시까지

**Comment by IMCHO** [comment]
https://www.notion.so/taeknology/71c6a6a9954a4c90be8f39c22b859908

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/Device.md

**Comment by jeffoio** [comment]
https://www.notion.so/b517ed9298e443349f3719ac4e26448d

**Comment by getBingsoo** [comment]
https://www.notion.so/Bounds-Frame-b0b808ff0dd94fbeb842e79259afe607
