### ISSUE TITLE
앱이 foreground에 있을 때와 background에 있을 때 어떤 제약사항이 있나요?

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#21]
2020년 10월 23일(금) 오후 3시까지

**Comment by IMCHO** [comment]
https://www.notion.so/taeknology/foreground-background-69cc5be44fd643ef9bc55391b2b5904a
그렇게 시간을 투자하지는 못했지만...관련 자료를 못 찾겠네요ㅠㅠ

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/Foreground-Background.md

**Comment by devejs** [comment]
https://devejs.github.io/ios/2020/10/23/ios-foreground-background.html

**Comment by jeffoio** [comment]
https://www.notion.so/foreground-background-7596576a8ef840e6bdee4841b01f2cba

**Comment by Minimoa** [comment]
https://www.notion.so/767473/foreground-background-21-6875cfa6afc54d39aeb63794804aeb3f

**Comment by seonyoung169** [comment]
https://www.notion.so/foreground-background-64b3eb608d7f495d85f4e89156410f15
