### ISSUE TITLE
상태 변화에 따라 다른 동작을 처리하기 위한 앱델리게이트 메서드들을 설명하시오.

### ISSUE THREAD

**Issue by devejs** [ios-study-boost/iOSInterviewquestions#22]
2020년 10월 27일(화) 오전 10시까지

**Comment by IMCHO** [comment]
https://www.notion.so/taeknology/368da60528ec4546a30a741037006182

**Comment by jeffoio** [comment]
https://www.notion.so/f4d034cca6fe416f91b23a5ffdd49836

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/App-Lifecycle.md

**Comment by Minimoa** [comment]
https://www.notion.so/767473/7c387110e5bf4440bfae551a83c0473c

**Comment by devejs** [comment]
https://devejs.github.io/ios/2020/10/26/ios-app-delegate.html

**Comment by seonyoung169** [comment]
https://www.notion.so/91989b5b18e54228894c442d423050fa
