### ISSUE TITLE
scene delegate에 대해 설명하시오.

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#23]
2020년 11월 5일(목) 오전 10시까지

**Comment by jeffoio** [comment]
https://www.notion.so/scene-delegate-cf3a0bf1daf246ddbdf07952b29b7e56

**Comment by devejs** [comment]
https://devejs.github.io/ios/2020/11/04/ios-scene-delegate.html

**Comment by Minimoa** [comment]
https://www.notion.so/767473/scene-delegate-f38edecda09943d3989d6437feff8b73

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/Scene-Delegate.md
