### ISSUE TITLE
앱이 In-Active 상태가 되는 시나리오를 설명하시오. 

### ISSUE THREAD

**Issue by devejs** [ios-study-boost/iOSInterviewquestions#24]
2020년 11월 6일(금) 오후 3시까지

**Comment by IMCHO** [comment]
https://www.notion.so/taeknology/In-Active-bb9f3adb71db47bead320321f331828d

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/In-Active.md

**Comment by Minimoa** [comment]
https://www.notion.so/767473/In-Active-6e553a9c57214591af904a16db8464b0

**Comment by jeffoio** [comment]
https://www.notion.so/In-Active-e7607a325d6c4656a006a13b33c63cf0
