### ISSUE TITLE
NSOperationQueue 와 GCD Queue 의 차이점을 설명하시오.

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#25]
2020년 11월 10일(화) 오전 10시까지

**Comment by IMCHO** [comment]
https://www.notion.so/taeknology/NSOperationQueue-GCD-Queue-7e1936a30ca346d9ba74e09c8d77d07a

**Comment by jeffoio** [comment]
https://www.notion.so/NSOperationQueue-GCD-Queue-7dee5f9bb82643d2a5b227eb0a768b61

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/NSOperationQueue-GCDQueue.md

**Comment by Minimoa** [comment]
https://www.notion.so/767473/NSOperationQueue-GCD-Queue-47dcd68c38a044ce8429e3051b4b93a7

**Comment by devejs** [comment]
https://devejs.github.io/ios/2020/11/09/ios-async-queue.html
