### ISSUE TITLE
GCD API 동작 방식과 필요성에 대해 설명하시오.

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#26]
2020년 11월 12일(목) 오전 10시 까지

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/GCD-API.md

**Comment by jeffoio** [comment]
https://www.notion.so/GCD-API-65882583e57f4d798a33ad8a25ac5fad

**Comment by Minimoa** [comment]
https://www.notion.so/767473/GCD-API-80c655af9c4d49bb94b278985de6ff79
