### ISSUE TITLE
자신만의 Custom View를 만들려면 어떻게 해야하는지 설명하시오.

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#27]
2020년 11월 13일(금) 오후 3시까지

**Comment by Minimoa** [comment]
https://www.notion.so/767473/Custom-View-4f86e42eaae94a8884d43c53e19ff8a7

**Comment by jeffoio** [comment]
https://www.notion.so/Custom-View-e2fb5387d5a941e881d4eb7f57a3f85e

**Comment by getBingsoo** [comment]
https://www.notion.so/Custom-View-865623660b0d4548a2929a8ffaac4355
