### ISSUE TITLE
iOS 앱을 만들고, User Interface를 구성하는 데 필수적인 프레임워크 이름은 무엇인가?

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#28]
2020년 11월 17일(화) 오전 10시까지

**Comment by Minimoa** [comment]
https://www.notion.so/767473/iOS-User-Interface-bb50a802de9949e59563e3b5d8f4c8de

**Comment by getBingsoo** [comment]
https://www.notion.so/iOS-User-Interface-b8014e53472e400ea4718cf750c1d833
