### ISSUE TITLE
Foundation Kit은 무엇이고 포함되어 있는 클래스들은 어떤 것이 있는지 설명하시오

### ISSUE THREAD

**Issue by jeffoio** [ios-study-boost/iOSInterviewquestions#29]
2020년 11월 19일(목) 오전 10시까지

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/Foundation.md

**Comment by jeffoio** [comment]
https://www.notion.so/Foundation-Kit-0ba454fb3e744ebe9be8a9ad1c6d06e1

**Comment by Minimoa** [comment]
https://www.notion.so/767473/Foundation-Kit-af69c351a7e4458cab0f7444821d9235
