### ISSUE TITLE
Struct 가 무엇이고 어떻게 사용하는지 설명하시오.

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#3]
2021년 2월 22일(월) 오후 8시까지

**Comment by IMCHO** [comment]
https://www.notion.so/taeknology/Struct-b61a6a2651dd4cc4a8436be472d80fe3

**Comment by jwonyLee** [comment]
https://www.notion.so/jwonylee/Struct-669ecdcf065f4aa5b567f8a8f4caf34c

**Comment by jeffoio** [comment]
https://www.notion.so/Struct-b8d5eefecf3f41c7be5cf43704fa5411

**Comment by kartmon61** [comment]
https://www.notion.so/Struct-578768189f584d098a25f70881c5bd10

**Comment by Minimoa** [comment]
https://www.notion.so/767473/Struct-5170f592b5ad4bd795eb5142611afd5a
