### ISSUE TITLE
Delegate란 무언인가 설명하고, retain 되는지 안되는지 그 이유를 함께 설명하시오.

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#30]
2020년 11월 20일(금) 오후 3시까지

**Comment by jeffoio** [comment]
https://www.notion.so/Delegate-retain-e2441039e3ba42afa8394679fb2785be

**Comment by Minimoa** [comment]
https://www.notion.so/767473/Delegate-retain-67055eba47de45dbb56152debdfc93f7

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/Delegate-retain.md
