### ISSUE TITLE
NotificationCenter 동작 방식과 활용 방안에 대해 설명하시오.

### ISSUE THREAD

**Issue by jeffoio** [ios-study-boost/iOSInterviewquestions#31]
2020년 11월 24일(화) 오전 10시까지

**Comment by jeffoio** [comment]
https://www.notion.so/NotificationCenter-f9c115b6c532451abd093d9f45e9309b

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/NotificationCenter.md

**Comment by seonyoung169** [comment]
https://www.notion.so/NotificationCenter-bcb6e10495fb42c1b2c51de6f6936995
