### ISSUE TITLE
UIKit 클래스들을 다룰 때 꼭 처리해야하는 애플리케이션 쓰레드 이름은 무엇인가?

### ISSUE THREAD

**Issue by jeffoio** [ios-study-boost/iOSInterviewquestions#32]
2020년 11월 26일(목) 오전 10시까지

**Comment by IMCHO** [comment]
https://www.notion.so/taeknology/UIKit-67e315d492e6466192f74e934a143dca

**Comment by Minimoa** [comment]
https://www.notion.so/767473/UIKit-759bf5b19ad0448ebdcc630090b02d64

**Comment by jeffoio** [comment]
https://www.notion.so/UIKit-eb3cd457ed2046718b762ee8bb9d819e

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/Application-thread.md

**Comment by seonyoung169** [comment]
https://www.notion.so/UIKit-0b396989e623422e9ad425b099901a45
