### ISSUE TITLE
TableView를 동작 방식과 화면에 Cell을 출력하기 위해 최소한 구현해야 하는 DataSource 메서드를 설명하시오.

### ISSUE THREAD

**Issue by IMCHO** [ios-study-boost/iOSInterviewquestions#33]

**Comment by IMCHO** [comment]
https://www.notion.so/taeknology/TableView-Cell-DataSource-2de90e805ebb43cf84baad6ea86c2593

**Comment by jeffoio** [comment]
https://www.notion.so/TableView-Cell-DataSource-3521e659863f411fa3220c443992038f

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/TableView.md

**Comment by Minimoa** [comment]
https://www.notion.so/767473/TableView-Cell-DataSource-f75300ec9103409f9ae60cf3161831ad
