### ISSUE TITLE
하나의 View Controller 코드에서 여러 TableView Controller 역할을 해야 할 경우 어떻게 구분해서 구현해야 하는지 설명하시오.

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#34]

**Comment by jeffoio** [comment]
https://www.notion.so/View-Controller-TableView-Controller-4b7f19987a814cde86ac732be1e50e86

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/two-TableView.md
