### ISSUE TITLE
App Bundle의 구조와 역할에 대해 설명하시오.

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#35]
2020년 12월 1일(화) 오후 7시까지

**Comment by jeffoio** [comment]
https://www.notion.so/App-Bundle-650ff04e917c4ef4980237d4f68f09a3

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/AppBundle.md
