### ISSUE TITLE
UIView 에서 Layer 객체는 무엇이고 어떤 역할을 담당하는지 설명하시오.

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#37]
2020년 12월 7일(월) 오후 7시까지

**Comment by jeffoio** [comment]
https://www.notion.so/UIView-Layer-d58bf9f0f9cd4aac8bed89abec292d2c

**Comment by getBingsoo** [comment]
https://www.notion.so/UIView-Layer-a50212c9a0f14ae4a64fc93a7eb33222

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/Layer.md
