### ISSUE TITLE
UIWindow 객체의 역할은 무엇인가?

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#38]
2020년 12월 8일(화) 오후 7시까지

**Comment by jeffoio** [comment]
https://www.notion.so/UIWindow-b00e9a2d27f34c4e877f9562cc60bb4b

**Comment by getBingsoo** [comment]
https://www.notion.so/UIWindow-30a07b7849574b20a95073037e949241 일단 올리고 보강해서 다시올릴게여..!
