### ISSUE TITLE
instance 메서드와 class 메서드의 차이점을 설명하시오.

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#4]
2020년 9월 15일(화) 오전 10시까지
\+ 2021년 2월 23일(화) 오후 8시까지

**Comment by IMCHO** [comment]
https://www.notion.so/taeknology/instance-class-fa41ed7a2bd44e54b3bc2c4ac306a8ac

**Comment by jeffoio** [comment]
https://www.notion.so/instance-class-02895d9a4fbc4e7d98fb355d541cbd30

**Comment by Minimoa** [comment]
https://www.notion.so/767473/instance-class-7a373627b2724babb79e32a5ee8c941e

**Comment by jwonyLee** [comment]
https://www.notion.so/jwonylee/instance-class-0caa78cdbd1e43e2a66e3061369d1e25

**Comment by devejs** [comment]
https://devejs.github.io/ios/2020/09/14/static-self.html

**Comment by kartmon61** [comment]
https://www.notion.so/instance-class-849e78f6654b4b27b130f5c986ec047b
