### ISSUE TITLE
모든 View Controller 객체의 상위 클래스는 무엇이고 그 역할은 무엇인가?

### ISSUE THREAD

**Issue by jeffoio** [ios-study-boost/iOSInterviewquestions#40]
2020년 12월 14일(월) 오후 7시까지

**Comment by getBingsoo** [comment]
https://www.notion.so/View-Controller-51c8c03a06f3455ab9b35c625e3bcb30

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/ViewController.md
