### ISSUE TITLE
앱의 콘텐츠나 데이터 자체를 저장/보관하는 특별한 객체를 무엇이라고 하는가?

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#43]
2020년 12월 21일(월) 오후 7시까지

**Comment by jeffoio** [comment]
https://www.notion.so/6a665a7020ce4992a4fe44bd93bdf444

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/Store.md

**Comment by Minimoa** [comment]
https://www.notion.so/767473/bb8ebcc15a9342ff8fc0fd1555e13f14
