### ISSUE TITLE
앱 화면의 콘텐츠를 표시하는 로직과 관리를 담당하는 객체를 무엇이라고 하는가?

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#44]
2020년 12월 28일(월) 오후 7시까지

**Comment by seonyoung169** [comment]
수정합니다! https://www.notion.so/iOS-InterView-Questions-10fc6ba92953429b85d0bbedc25c58ee

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/UIViewController.md

**Comment by jeffoio** [comment]
https://www.notion.so/32b4a19f75d04f33ad92cdde611b189e
