### ISSUE TITLE
Swift의 클로저와 Objective-C의 블록은 어떤 차이가 있는가?

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#45]
2020년 12월 29일(화) 오후 7시까지

**Comment by seonyoung169** [comment]
https://www.notion.so/Swift-Objective-C-2cca1483449b4c2c9dd65e4ab18f6d10

**Comment by jeffoio** [comment]
https://www.notion.so/Swift-Objective-C-863502fbfd6b4319b1239b3302b08198

**Comment by Minimoa** [comment]
https://www.notion.so/767473/Swift-Objective-C-a040f11e6b5e489cbb7f7e88176a9a65

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/Closure-Block.md
