### ISSUE TITLE
App의 Not running, Inactive, Active, Background, Suspended에 대해 설명하시오.

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#46]
2020년 12월 31일(목) 오후 7시까지

**Comment by seonyoung169** [comment]
https://www.notion.so/App-Not-running-Inactive-Active-Background-Suspended-2ae3920c8d544c86b118158515bb8b2a

**Comment by jeffoio** [comment]
https://www.notion.so/App-Not-running-Inactive-Active-Background-Suspended-bd578b9be7ef408aabc44897ef1140f5

**Comment by Minimoa** [comment]
https://www.notion.so/767473/App-Not-running-Inactive-Active-Background-Suspended-3ae80dc5db49408fb63817a06532e4e0
