### ISSUE TITLE
App thinning에 대해서 설명하시오.

### ISSUE THREAD

**Issue by jeffoio** [ios-study-boost/iOSInterviewquestions#47]
2021년 1월 6일(수) 오후 7시까지

**Comment by seonyoung169** [comment]
https://www.notion.so/App-thinning-6968cfd296a148f89a97d407673a6cae

**Comment by jeffoio** [comment]
https://www.notion.so/App-thinning-53aef02e0ee84de693e7d4a5a4f3fa97

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/App-thinning.md

**Comment by Aileen-HyunjiSong** [comment]
https://www.notion.so/App-Thinning-b466cc5b5a32407c8353d2e434524ba1

**Comment by getBingsoo** [comment]
https://www.notion.so/App-thinning-b200f0f0e853476cb98e1be602a34854
