### ISSUE TITLE
Global DispatchQueue 의 Qos 에는 어떤 종류가 있는지, 각각 어떤 의미인지 설명하시오.

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#48]
2021년 1월 11일(월) 오후 7시까지

**Comment by seonyoung169** [comment]
https://www.notion.so/Global-DispatchQueue-Qos-2b1c040081364b1285170db825a3e325

**Comment by Minimoa** [comment]
계속 밖이라서 참여 못할 것 같습니다

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/QoS.md

**Comment by jeffoio** [comment]
https://www.notion.so/Global-DispatchQueue-Qos-58eaa650b3ec4adb90d20cee524492cd
