### ISSUE TITLE
오토레이아웃을 코드로 작성하는 방법은 무엇인가? (3가지)

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#49]
2021년 1월 12일(화) 오후 7시까지

**Comment by seonyoung169** [comment]
https://www.notion.so/AutoLayout-0596746b5f794f27a32c803717e9b6e3

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/Autolayout-code.md

**Comment by jeffoio** [comment]
https://www.notion.so/3-7035a1caea5e44ba982b84983dc02a01
