### ISSUE TITLE
Delegate 패턴을 활용하는 경우를 예를 들어 설명하시오.

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#5]
2020년 9월 17일(목) 오전 10시 까지
\+ 2021년 2월 23일(화) 오후 8시까지

**Comment by IMCHO** [comment]
https://www.notion.so/taeknology/Delegate-7d9736d4a78c4e9287baf31daff1fa3d

**Comment by jwonyLee** [comment]
https://www.notion.so/jwonylee/Delegate-1ea37c778c3544199cf1648eb4b80d86

**Comment by Minimoa** [comment]
https://www.notion.so/767473/Delegate-06131caedb954cd48092362484a9dbb1

**Comment by jeffoio** [comment]
https://www.notion.so/Delegate-9d4949c2fb6f4ff48834313c8fa087ec

**Comment by kartmon61** [comment]
https://www.notion.so/Delegate-a91c5ea07ea5437396126106b01e46d7
