### ISSUE TITLE
hugging, resistance에 대해서 설명하시오.

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#50]
2021년 1월 14일(목) 오후 7시까지

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/hugging-resistance.md

**Comment by seonyoung169** [comment]
https://www.notion.so/hugging-resistance-a915df1940764914a18e49113fd66868

**Comment by jeffoio** [comment]
https://www.notion.so/hugging-resistance-47e56d8c47bf48b786a32eb24943dff2
