### ISSUE TITLE
스토리보드를 이용했을때의 장단점을 설명하시오.

### ISSUE THREAD

**Issue by jeffoio** [ios-study-boost/iOSInterviewquestions#52]
2021년 1월 19일(화) 오후 7시까지

**Comment by Minimoa** [comment]
https://www.notion.so/767473/13da4da120ab4c1a9f32b7902ee5e440

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/Storyboard.md

**Comment by Aileen-HyunjiSong** [comment]
https://www.notion.so/c737ac31ac7c472ba3fe52ee680d06ec

**Comment by jeffoio** [comment]
https://www.notion.so/052b4d0dc5ec48248acf06e46d0e43ee
