### ISSUE TITLE
Safearea에 대해서 설명하시오.

### ISSUE THREAD

**Issue by jeffoio** [ios-study-boost/iOSInterviewquestions#53]
2021년 1월 21일(목) 오후 7시까지

**Comment by jeffoio** [comment]
https://www.notion.so/Safearea-6e2b287984de4e31809c446040b77254

**Comment by getBingsoo** [comment]
https://www.notion.so/Safearea-af3d352f8b9a4961b9e508e06806b816

**Comment by seonyoung169** [comment]
https://www.notion.so/SafeArea-c9848611ed994cdda5008c6827e578a6
