### ISSUE TITLE
Left Constraint 와 Leading Constraint 의 차이점을 설명하시오.

### ISSUE THREAD

**Issue by jeffoio** [ios-study-boost/iOSInterviewquestions#54]
2021년 1월 25일(월) 오후 7시까지

**Comment by seonyoung169** [comment]
https://www.notion.so/Left-Constraint-Leading-Constraint-4d69966cb8bf4d83812d338ea3e5ffce

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/Left-Constraint-Leading-Constraint.md

**Comment by jeffoio** [comment]
https://www.notion.so/Left-Constraint-Leading-Constraint-ec03ec2a47804efaac3be900393ca145
