### ISSUE TITLE
ARC란 무엇인지 설명하시오.

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#55]
2021년 1월 26일(화) 오후 7시까지

**Comment by seonyoung169** [comment]
https://www.notion.so/ARC-ced8ef568b2d429cb22e7ee05b54da72

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/ARC.md

**Comment by kartmon61** [comment]
https://www.notion.so/ARC-282a3d2bbdb64ba9b844ad265eded425
