### ISSUE TITLE
Retain Count 방식에 대해 설명하시오.

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#58]
2021년 1월 28일(목) 오후 7시까지

**Comment by jeffoio** [comment]
https://www.notion.so/Retain-Count-5746d886d39843b482c0a9a02b9f5f0e

**Comment by getBingsoo** [comment]
https://www.notion.so/Retain-Count-0ab6f1a494d9476e906a5a0a901ab29b
