### ISSUE TITLE
Strong 과 Weak 참조 방식에 대해 설명하시오.

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#59]
2021년 2월 1일(월) 오후 7시까지

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/Strong-Weak.md

**Comment by jeffoio** [comment]
https://www.notion.so/Strong-Weak-5978cb133fcf4af499ec657f3750a507

**Comment by seonyoung169** [comment]
https://www.notion.so/Strong-Weak-2809e8170b5f46c18a9ffe67a96b7c1a

**Comment by getBingsoo** [comment]
https://www.notion.so/Strong-Weak-8d2f1d3eaeca431fa573ae056ebe7178
