### ISSUE TITLE
Singleton 패턴을 활용하는 경우를 예를 들어 설명하시오.

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#6]
2020년 9월 18일(금) 오후 3시 30분까지

**Comment by IMCHO** [comment]
https://www.notion.so/taeknology/Singleton-e3154042414b4af5902bd1e2cf19d272

**Comment by Minimoa** [comment]
https://www.notion.so/767473/Singleton-d767807280ec448f96319cbc270d4a7c

**Comment by jwonyLee** [comment]
https://www.notion.so/jwonylee/Singleton-7f35b34fbb684e33bffabf909337bec1

**Comment by jeffoio** [comment]
https://www.notion.so/Singleton-b7924b1b5a974240bdd8e41798b85ca6

**Comment by kartmon61** [comment]
https://www.notion.so/Singleton-2c515cce2f4e4888b393f4e08db7222b

**Comment by devejs** [comment]
https://devejs.github.io/ios/2020/09/17/singleton.html

**Comment by seonyoung169** [comment]
https://www.notion.so/Singleton-cc026b218bc249b7a36386a144d7a3c0
