### ISSUE TITLE
ARC 대신 Manual Reference Count 방식으로 구현할 때 꼭 사용해야 하는 메서드들을 쓰고 역할을 설명하시오.

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#60]
2021년 2월 4일(목) 오후 7시까지

**Comment by seonyoung169** [comment]
https://www.notion.so/ARC-Manual-Reference-Count-04746bd1f3854269a8b25fe868958e7a

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/MRC-method.md
