### ISSUE TITLE
retain 과 assign 의 차이점을 설명하시오.

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#61]
2021년 2월 8일(월) 오후 7시까지

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/retain-assign.md

**Comment by jeffoio** [comment]
https://www.notion.so/retain-assign-4596c7b1feaa4c2b9d5e9f85b6f28449

**Comment by getBingsoo** [comment]
https://www.notion.so/retain-assign-74c083aafea543fbbcc3a0e1896b76ea
