### ISSUE TITLE
강한 순환 참조 (Strong Reference Cycle) 는 어떤 경우에 발생하는지 설명하시오.

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#63]
2021년 2월 15일(월) 오후 7시까지

**Comment by seonyoung169** [comment]
https://www.notion.so/Strong-Reference-Cycle-35d8ea15da464c0fbb5e57410746e663

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/Strong-Reference-Cycle.md

**Comment by jeffoio** [comment]
https://www.notion.so/180b132b7d934df1b9375c661faadc72
