### ISSUE TITLE
특정 객체를 autorelease 하기 위해 필요한 사항과 과정을 설명하시오.

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#64]
2021년 2월 15일(화) 오후 7시까지

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/autorelease.md

**Comment by jeffoio** [comment]
https://www.notion.so/autorelease-pool-74d59b49ddab4dd8b002b071bb92b2f6
