### ISSUE TITLE
Autorelease Pool을 사용해야 하는 상황을 두 가지 이상 예로 들어 설명하시오.

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#65]
2021년 2월 16일(화) 오후 7시까지

**Comment by seonyoung169** [comment]
https://www.notion.so/Autorelease-Pool-f79e85136eaa4a0c8a948887f8558f54

**Comment by jwonyLee** [comment]
https://github.com/jwonyLee/TIL/blob/master/iOS/Interview/Autorelease-Pool.md

**Comment by jeffoio** [comment]
https://www.notion.so/autorelease-pool-74d59b49ddab4dd8b002b071bb92b2f6
