### ISSUE TITLE
KVO 동작 방식에 대해 설명하시오.

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#7]
2020년 9월 22일(화) 오전 10시까지

**Comment by IMCHO** [comment]
https://www.notion.so/taeknology/KVO-eea8d7c851734d7ba1b60ddd654db52b

**Comment by jwonyLee** [comment]
https://www.notion.so/jwonylee/KVO-54e8f30d402a456493ca6435a0c3d89b

**Comment by jeffoio** [comment]
https://www.notion.so/KVO-193378c586884ebbae601aa9c3db998a

**Comment by devejs** [comment]
https://devejs.github.io/ios/2020/09/21/swift-kvo.html

**Comment by Minimoa** [comment]
https://www.notion.so/767473/KVO-8b9685cba1b34371ba776c8cba982ab0

**Comment by kartmon61** [comment]
https://www.notion.so/KVO-c35d8c8580124c3790039b8228915eb7

**Comment by seonyoung169** [comment]
https://www.notion.so/KVO-128aee8b7b894c92ace00ba7649b6397
