### ISSUE TITLE
Delegates와 Notification 방식의 차이점에 대해 설명하시오.

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#8]
2020년 9월 24일(목) 오전 10시 까지

**Comment by IMCHO** [comment]
https://www.notion.so/taeknology/Delegates-Notification-d42fb9bd3fb74f7785d0d18ba2609bcc

**Comment by jwonyLee** [comment]
https://www.notion.so/jwonylee/Delegates-Notification-c34d3371dc464efe9b18f2d842a866c9

**Comment by devejs** [comment]
https://devejs.github.io/ios/2020/09/23/notification_delegation.html

**Comment by Minimoa** [comment]
https://www.notion.so/767473/Delegates-Notification-ae672fa85c354d19b6a8f30b411cf8c4

**Comment by jeffoio** [comment]
https://www.notion.so/Delegates-Notification-d17baa645f5f471f91971ca13facec50

**Comment by seonyoung169** [comment]
https://www.notion.so/Delegate-Notification-a082e3491ae546009ae95a684de0cd14
