### ISSUE TITLE
멀티 쓰레드로 동작하는 앱을 작성하고 싶을 때 고려할 수 있는 방식들을 설명하시오.

### ISSUE THREAD

**Issue by jwonyLee** [ios-study-boost/iOSInterviewquestions#9]
2020년 9월 25일(금) 오후 3시 까지

**Comment by IMCHO** [comment]
https://www.notion.so/taeknology/7cbd401ce83e45d2a1152b342c574799

**Comment by Minimoa** [comment]
https://www.notion.so/767473/2a6d91af9c534ea791d26a96d60158aa

**Comment by jwonyLee** [comment]
https://www.notion.so/jwonylee/8ff8baca574d4bd9882a2b0c7764c5c9

**Comment by kartmon61** [comment]
https://www.notion.so/868ec584a6d14851a5c6d74ec4c1c791

**Comment by jeffoio** [comment]
https://www.notion.so/286e419e66484f92ad188649b788a7fd

**Comment by devejs** [comment]
https://devejs.github.io/ios/2020/09/25/multi-thread.html

**Comment by seonyoung169** [comment]
https://www.notion.so/be56b1bb88bc44f594a73c380d99e066
